---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  {{- with .Values.entryPoints }}
  entryPoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  routes:
    - match: {{ .Values.ingress.match | default "PathPrefix(`/api`)" | quote }}
      kind: Rule
      services:
        - name: {{ include "api.name" . }}
          port: {{ include "service.port" . }}
