package facts

import (
	"math/rand"
	"time"
)

// RandomFact returns a random cat fact
//
// Taken from:
// https://github.com/vadimdemedes/cat-facts/blob/49dfacbe897b369f5403565b4d17614e459c468c/cat-facts.json
func RandomFact() string {
	facts := []string{
		"A Japanese cat figurine called Maneki-Neko is believed to bring good luck",
		"A Selkirk slowly loses its naturally-born curly coat, but it grows again when the cat is around 8 months",
		"A cat almost never meows at another cat, mostly just humans",
		"A cat can jump up to five times its own height in a single bound",
		"A cat can reach up to five times its own height per jump",
		"A cat can travel at a top speed of approximately 31 mph (49 km) over a short distance",
		"A cat cannot climb head first down a tree because its claws are curved the wrong way",
		"A cat has 230 bones in its body",
		"A cat usually has about 12 whiskers on each side of its face",
		"A cat's back is extremely flexible because it has up to 53 loosely fitting vertebrae",
		"A cat's brain is biologically more similar to a human brain than it is to a dog's",
		"A cat's eyesight is both better and worse than humans",
		"A cat's field of vision does not cover the area right under its nose",
		"A cat's hearing is better than a dog's",
		"A cat's heart beats almost double the rate of a human heart, from 110 to 140 beats per minute",
		"A cat's heart beats nearly twice as fast as a human heart",
		"A cat's jaw can't move sideways, so a cat can't chew large chunks of food",
		"A cat's meow is usually not directed at another cat, but at a human. To communicate with other cats, they will usually hiss, purr and spit.",
		"A female cat is also known to be called a queen or a molly",
		"A fingerprint is to a human as a nose is to a cat",
		"A group of cats is called a clowder",
		"A group of kittens is called a kindle, and clowder is a term that refers to a group of adult cats",
		"A third of cats' time spent awake is usually spent cleaning themselves",
		"According to the Association for Pet Obesity Prevention (APOP), about 50 million of our cats are overweight",
		"According to the Guinness World Records, the largest domestic cat litter totaled at 19 kittens, four of them stillborn",
		"According to the International Species Information Service, there are only three Marbled Cats still in existence worldwide.  One lives in the United States.",
		"Although it is known to be the tailless cat, the Manx can be born with a stub or a short tail",
		"Ancient Egyptians first adored cats for their finesse in killing rodents—as far back as 4,000 years ago",
		"Approximately 24 cat skins can make a coat",
		"Approximately 40,000 people are bitten by cats in the U.S.",
		"Around the world, cats take a break to nap —a catnap— 425 million times a day",
		"As temperatures rise, so do the number of cats. Cats are known to breed in warm weather, which leads many animal advocates worried about the plight of cats under Global Warming.",
		"Because of widespread cat smuggling in ancient Egypt, the exportation of cats was a crime punishable by death",
		"Black cats aren't an omen of ill fortune in all cultures. In the UK and Australia, spotting a black cat is good luck",
		"Blue-eyed cats have a high tendency to be deaf, but not all cats with blue eyes are deaf",
		"Bobtails are known to have notably short tails -- about half or a third the size of the average cat",
		"Call them wide-eyes: cats are the mammals with the largest eyes",
		"Cat's back claws aren't as sharp as the claws on their front paws",
		"Cats CAN be lefties and righties, just like us. More than forty percent of them are, leaving some ambidextrous",
		"Cats actually have dreams, just like us. They start dreaming when they reach a week old",
		"Cats are extremely sensitive to vibrations",
		"Cats are the most popular pet in North American Cats are North America's most popular pets",
		"Cats are unable to detect sweetness in anything they taste",
		"Cats came to the Americas from Europe as pest controllers in the 1750s",
		"Cats can pick up on your tone of voice, so sweet-talking to your cat has more of an impact than you think",
		"Cats hate the water because their fur does not insulate well when it's wet",
		"Cats have 24 more bones than humans",
		"Cats have 32 muscles that control the outer ear",
		"Cats have a 5 toes on their front paws and 4 on each back paw",
		"Cats have a strong aversion to anything citrus",
		"Cats have about 20,155 hairs per square centimeter",
		"Cats have over 100 sounds in their vocal repertoire, while dogs only have 10",
		"Cats have the cognitive ability to sense a human's feelings and overall mood",
		"Cats have the skillset that makes them able to learn how to use a toilet",
		"Cats make about 100 different sounds",
		"Cats prefer their food at room temperature—not too hot, not too cold",
		"Cats show affection and mark their territory by rubbing on people. Glands on their face, tail and paws release a scent to make its mark",
		"Cats sleep 16 hours of any given day",
		"Cats spend nearly 1/3 of their waking hours cleaning themselves",
		"Cats use their whiskers to measure openings, indicate mood and general navigation",
		"Cats who eat too much tuna can become addicted, which can actually cause a Vitamin E deficiency",
		"Cats would rather starve themselves than eat something they don't like. This means they will refuse an unpalatable -- but nutritionally complete -- food for a prolonged period",
		"Cats' rough tongues enable them to clean themselves efficiently and to lick clean an animal bone",
		"Caution during Christmas: poinsettias may be festive, but they’re poisonous to cats",
		"Collectively, kittens yawn about 200 million time per hour",
		"Despite appearing like a wild cat, the Ocicat does not have an ounce of wild blood",
		"During the Middle Ages, cats were associated with witchcraft",
		"Each side of a cat's face has about 12 whiskers",
		"Eating grass rids a cats' system of any fur and helps with digestion",
		"Elvis Presley’s Chinese name is Mao Wong, or Cat King",
		"Every year, nearly four million cats are eaten in Asia",
		"Female cats tend to be right pawed, while male cats are more often left pawed",
		"Foods that should not be given to cats include onions, garlic, green tomatoes, raw potatoes, chocolate, grapes, and raisins",
		"Genetically, cats' brains are more similar to that of a human than a dog's brain",
		"Grown cats have 30 teeth",
		"If you killed a cat in the ages of Pharaoh, you could've been put to death",
		"If your cat's eyes are closed, it's not necessarily because it's tired. A sign of closed eyes means your cat is happy or pleased",
		"In 1888, more than 300,000 mummified cats were found an Egyptian cemetery",
		"In Japan, cats are thought to have the power to turn into super spirits when they die",
		"In North America, cats are a more popular pet than dogs. Nearly 73 million cats and 63 million dogs are kept as household pets",
		"In homes with more than one cat, it is best to have cats of the opposite sex. They tend to be better housemates.",
		"In multi-pet households, cats are able to get along especially well with dogs if they're introduced when the cat is under 6 months old and the dog is under one year old",
		"In one litter of kittens, there could be multiple father cats",
		"It has been said that the Ukrainian Levkoy has the appearance of a dog, due to the angles of its face",
		"It is important to include fat in your cat's diet because they're unable to make the nutrient in their bodies on their own",
		"Landing on all fours is something typical to cats thanks to the help of their eyes and special balance organs in their inner ear. These tools help them straighten themselves in the air and land upright on the ground.",
		"Maine Coons are the most massive breed of house cats. They can weigh up to around 24 pounds",
		"Many Egyptians worshipped the goddess Bast, who had a woman's body and a cat's head",
		"Many cat owners think their cats can read their minds",
		"Mohammed loved cats and reportedly his favorite cat, Muezza, was a tabby",
		"Most cat litters contain four to six kittens",
		"Most cats don't have eyelashes",
		"Most cats give birth to a litter of between one and nine kittens",
		"Most cats had short hair until about 100 years ago, when it became fashionable to own cats and experiment with breeding",
		"Most cats will eat 7 to 20 small meals a day. This interesting fact is brought to you by Nature's Recipe®",
		"Most kittens are born with blue eyes, which then turn color with age",
		"On average, cats spend 2/3 of every day sleeping",
		"One of Muhammad's companions was nicknamed Abu Hurairah, or Father of the Kitten, because he loved cats",
		"Outdoor cats' lifespan averages at about 3 to 5 years; indoor cats have lives that last 16 years or more",
		"Perhaps the oldest cat breed on record is the Egyptian Mau, which is also the Egyptian language's word for cat",
		"Ragdoll cats live up to their name: they will literally go limp, with relaxed muscles, when lifted by a human",
		"Rather than nine months, cats' pregnancies last about nine weeks",
		"Researchers are unsure exactly how a cat purrs",
		"Sir Isaac Newton, among his many achievements, invented the cat flap door",
		"Smuggling a cat out of ancient Egypt was punishable by death",
		"Some cats can survive falls from as high up as 65 feet or more",
		"Some cats have survived falls of over 20 meters",
		"Sometimes called the Canadian Hairless, the Sphynx is the first cat breed that has lasted this long—the breed has been around since 1966",
		"Talk about Facetime: Cats greet one another by rubbing their noses together",
		"Teeth of cats are sharper when they're kittens. After six months, they lose their needle-sharp milk teeth",
		"The Egyptian Mau is probably the oldest breed of cat",
		"The Maine Coon is appropriately the official State cat of its namesake state",
		"The Snow Leopard, a variety of the California Spangled Cat, always has blue eyes",
		"The biggest wildcat today is the Siberian Tiger",
		"The cat who holds the record for the longest non-fatal fall is Andy",
		"The color of York Chocolates becomes richer with age. Kittens are born with a lighter coat than the adults",
		"The earliest ancestor of the modern cat lived about 30 million years ago",
		"The first cat show was organized in 1871 in London",
		"The largest cat breed by mean weight is the Savannah, at 10kg",
		"The richest cat is Blackie who was left £15 million by his owner, Ben Rea",
		"The smallest pedigreed cat is a Singapura, which can weigh just 4 lbs",
		"The smallest wildcat today is the Black-footed cat",
		"The technical term for a cat's hairball is a bezoar",
		"The two outer layers of a cat's hair are called, respectively, the guard hair and the awn hair",
		"The world's most fertile cat, whose name was Dusty, gave birth to 420 kittens in her lifetime",
		"There are more than 500 million domestic cats in the world",
		"Today, cats are living twice as long as they did just 50 years ago",
		"Twenty-five percent of cat owners use a blow drier on their cats after bathing",
		"Two members of the cat family are distinct from all others: the clouded leopard and the cheetah",
		"Unlike dogs, cats do not have a sweet tooth",
		"Unlike most other cats, the Turkish Van breed has a water-resistant coat and enjoys being in water",
		"Want to call a hairball by its scientific name? Next time, say the word bezoar",
		"Webbed feet on a cat? The Peterbald's got 'em! They make it easy for the cat to get a good grip on things with skill",
		"When a cat chases its prey, it keeps its head level",
		"When a family cat died in ancient Egypt, family members would mourn by shaving off their eyebrows",
		"When a household cat died in ancient Egypt, its owners showed their grief by shaving their eyebrows",
	}
	rand.Seed(time.Now().Unix())
	n := rand.Int() % len(facts)
	return facts[n]
}
