name: "Continuous Deployment"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency: "cd"
    steps:
      - uses: actions/checkout@v2
      # - uses: asdf-vm/actions/install@v1
      - name: Install pulumi dependencies
        working-directory: deployment/pulumi
        run: |
          yarn install --frozen-lockfile
      - name: Run pulumi update
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
        run: |
          aws eks update-kubeconfig --name usw2-r
          pulumi -s prod --cwd deployment/pulumi up --yes --skip-preview --suppress-outputs --suppress-permalink
